@extends('layouts.app')
@section('title',$assignment->title)
@section('content')
<div class="page-head"><div><h1>{{ $assignment->title }}</h1><p>{{ $assignment->teachingAssignment->subject->name }} · {{ $assignment->teachingAssignment->teacher->user->name }}</p></div><span class="badge {{ now()->greaterThan($assignment->due_at)?'badge-danger':'badge-info' }}">Tenggat {{ $assignment->due_at->format('d M Y H:i') }}</span></div>
<div class="card"><h2 class="section-title">Instruksi</h2><p>{!! nl2br(e($assignment->description ?: 'Tidak ada instruksi tambahan.')) !!}</p>@if($assignment->file_path)<a class="btn" href="{{ route('files.assignments',$assignment) }}">Download Lampiran</a>@endif</div>
@if($submission)<div class="card"><h2 class="section-title">Pengumpulan Saya</h2><p>Dikumpulkan: {{ $submission->submitted_at->format('d M Y H:i') }}</p>@if($submission->file_path)<a href="{{ route('files.submissions',$submission) }}">{{ $submission->file_name }}</a>@endif<p>{{ $submission->note }}</p>@if($submission->score !== null)<div class="alert alert-success"><strong>Nilai: {{ $submission->score }} / {{ $assignment->max_score }}</strong><br>{{ $submission->feedback }}</div>@endif</div>@endif
@if(now()->lessThanOrEqualTo($assignment->due_at))<div class="card"><h2 class="section-title">{{ $submission?'Ganti Pengumpulan':'Kumpulkan Tugas' }}</h2><form method="POST" enctype="multipart/form-data" action="{{ route('student.assignments.submit',$assignment) }}">@csrf<div class="field"><label>File Jawaban</label><input type="file" name="file"><small>Opsional jika jawaban ditulis pada catatan. Maks. {{ number_format(config('narsis.upload_max_kb', 4096) / 1024, 1) }} MB.</small></div><div class="field"><label>Catatan / Jawaban Teks</label><textarea name="note">{{ old('note',$submission?->note) }}</textarea></div><button class="btn btn-primary">{{ $submission?'Perbarui Pengumpulan':'Kumpulkan' }}</button></form></div>@else<div class="alert alert-error">Tenggat pengumpulan telah berakhir.</div>@endif
<a class="btn" href="{{ route('student.assignments.index') }}">Kembali</a>
@endsection
